### PR TITLE
feat: add --fix prefix support and unified command selection logic

### LINKED ISSUE #14: Add an autofix flag
There should be either `--fix` or `--autofix` flag (former is potentially more standard) present in the CLI options. This should then trigger an additional script for any tools that support it (similar to the `looseCommand` option). That way, it will be configurable by end-users to have any command, such as `prettier --write` or `eslint --fix`.

### PR DESCRIPTION
**Pull request by AkhmetovOlzhass**
## Summary

This PR adds support for the `--fix` flag, allowing tools such as Prettier,
ESLint, MarkdownLint, and Knip to run their configured fix commands before
performing the standard checks.

## Changes included

- Added `isFixMode` to CLI run options
- Updated `selectCommand` to support fix > loose > base command priority
- Extended all step configurations to define `fixCommand` where applicable
- Updated tests for the new behaviour

## Why this is needed

This implements the autofix functionality requested in the discussion and
provides a clean, consistent command-selection mechanism.

## Link to Issue

Fixes #14

### CODE REVIEW

File: src/helpers.ts [hunk 1]
```diff
@@ -33,10 +35,15 @@ export const decorateLabel = (
 export const selectCommand = (
   baseCommand: string,
   looseCommand: string | undefined,
-  isLooseMode: boolean
+  fixCommand: string | undefined,
+  runOptions: RunOptions
```
Comment (MaximSrour) [inline src/helpers.ts]: Nice cleanup!

File: src/helpers.test.ts [hunk 2]
```diff
@@ -24,20 +25,48 @@ describe("decorateLabel", () => {
 });
 
 describe("selectCommand", () => {
-  it("returns base command when loose mode disabled", () => {
-    expect(selectCommand("npm run lint", "npm run lint:loose", false)).toBe(
-      "npm run lint"
-    );
+  const base = "npm run lint";
+  const loose = "npm run lint:loose";
+  const fix = "npm run lint:fix";
```
Comment (MaximSrour) [inline src/helpers.test.ts]: These variables need to be a little clearer:

```
const baseCommand = ...
const looseCommand = ...
const fixCommand = ...
```

File: src/helpers.test.ts [hunk 3]
```diff
@@ -24,20 +25,48 @@ describe("decorateLabel", () => {
...
+
+  const makeOptions = (isLoose: boolean, fix: boolean): RunOptions => {
```
Comment (MaximSrour) [inline src/helpers.test.ts]: The `fix` param should be `isFix` at least, to keep it in line with `isLoose`.

**Review by MaximSrour — APPROVED** [review]
